// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"contract/internal/service/internal/dao/internal"
)

// internalRechargesDao is internal type for wrapping internal DAO implements.
type internalRechargesDao = *internal.RechargesDao

// rechargesDao is the data access object for table recharges.
// You can define custom methods on it to extend its functionality as you wish.
type rechargesDao struct {
	internalRechargesDao
}

var (
	// Recharges is globally public accessible object for table recharges operations.
	Recharges = rechargesDao{
		internal.NewRechargesDao(),
	}
)

// Fill with you ideas below.
