// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Accounts is the golang structure of table accounts for DAO operations like Where/Data.
type Accounts struct {
	g.Meta    `orm:"table:accounts, do:true"`
	Id        interface{} //
	Address   interface{} //
	Coin      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
