// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Recharges is the golang structure of table recharges for DAO operations like Where/Data.
type Recharges struct {
	g.Meta    `orm:"table:recharges, do:true"`
	Id        interface{} //
	Address   interface{} //
	GameCoin  interface{} //
	TokenCoin interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
