// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RechargesDao is the data access object for table recharges.
type RechargesDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns RechargesColumns // columns contains all the column names of Table for convenient usage.
}

// RechargesColumns defines and stores column names for table recharges.
type RechargesColumns struct {
	Id        string //
	Address   string //
	GameCoin  string //
	TokenCoin string //
	CreatedAt string //
	UpdatedAt string //
}

//  rechargesColumns holds the columns for table recharges.
var rechargesColumns = RechargesColumns{
	Id:        "id",
	Address:   "address",
	GameCoin:  "game_coin",
	TokenCoin: "token_coin",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewRechargesDao creates and returns a new DAO object for table data access.
func NewRechargesDao() *RechargesDao {
	return &RechargesDao{
		group:   "default",
		table:   "recharges",
		columns: rechargesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RechargesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RechargesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RechargesDao) Columns() RechargesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RechargesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RechargesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RechargesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
